### ISSUE TITLE
AttributeError: 'NormBLR' object has no attribute 'theta0'

### ISSUE THREAD

**Issue by zzstefan** [amarquand/PCNtoolkit#100]
I was testing the code in https://amarquand.github.io/PCNtoolkit/doc/build/html/pages/BLR_normativemodel_protocol.html.

And I found the errors shown as below:
Processing data in /normative modeling/ROI_models/lh_MeanThickness_thickness/resp_tr.txt
Estimating model  1 of 1
configuring BLR ( order 1 )
Using default hyperparameters
Traceback (most recent call last):
  File "/home/.conda/envs/test/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-fa5e777aff9d>", line 1, in <module>
    yhat_te, s2_te, nm, Z, metrics_te = estimate(cov_file_tr,
  File "/home/.conda/envs/test/lib/python3.8/site-packages/pcntoolkit/normative.py", line 449, in estimate
    nm = norm_init(Xz_tr, Yz_tr[:, i], alg=alg, **kwargs)
  File "/home/.conda/envs/test/lib/python3.8/site-packages/pcntoolkit/normative_model/norm_utils.py", line 18, in norm_init
    nm = NormBLR(X=X, y=y, theta=theta, **kwargs)
  File "/home/.conda/envs/test/lib/python3.8/site-packages/pcntoolkit/normative_model/norm_blr.py", line 125, in __init__
    self.theta = self.theta0

Can you help check with that?

**Comment by amarquand** [comment]
Hi - thanks for reporting this. This is a known issue and we have fixed it (currently on the dev branch). We are finalising the testing and will release a new version in the next week or so. If you can't wait that long, you can already pull version 0.26 from the dev branch
