### ISSUE TITLE
Error when testing  up PCNtoolkit-0.18

### ISSUE THREAD

**Issue by Sabryr** [amarquand/PCNtoolkit#48]
After installing, I get the following when trying to load the package 

-bash-4.2$ python -c "import pcntoolkit as pk;print(pk.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cluster/projects/p33/conda/normative_modeling/0.18/PCNtoolkit-0.18/pcntoolkit/__init__.py", line 3, in <module>
    from . import gp
  File "/cluster/projects/p33/conda/normative_modeling/0.18/PCNtoolkit-0.18/pcntoolkit/gp.py", line 15, in <module>
    from pcntoolkit.utils import squared_dist
  File "/cluster/projects/p33/conda/normative_modeling/0.18/PCNtoolkit-0.18/pcntoolkit/utils.py", line 17, in <module>
    import pymc3 as pm
  File "/cluster/projects/p33/conda/normative_modeling/0.18/lib/python3.7/site-packages/pymc3-3.11.1-py3.7.egg/pymc3/__init__.py", line 39, in <module>
    __set_compiler_flags()
  File "/cluster/projects/p33/conda/normative_modeling/0.18/lib/python3.7/site-packages/pymc3-3.11.1-py3.7.egg/pymc3/__init__.py", line 35, in __set_compiler_flags
    current = theano.config.gcc__cxxflags
AttributeError: 'TheanoConfigParser' object has no attribute 'gcc__cxxflags'

**Comment by amarquand** [comment]
Hi - this looks like a Theano version issue. Could you please try with Theano==1.0.5 ?
