### ISSUE TITLE
Failed to import pcntoolkit with numpy>=1.23

### ISSUE THREAD

**Issue by gkane26** [amarquand/PCNtoolkit#91]
Hello,

pcntoolkit fails to import with numpy version 1.23 or later (see full traceback below). Downgrading to numpy==1.22.4 fixes the issue. It looks like pymc==3.9.3 calls numpy.asscalar, [which was removed from the numpy library in version 1.23](https://numpy.org/doc/stable/release/1.23.0-notes.html) (it's deprecated but still present in 1.22).

```
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/model/gp.py", line 15, in <module>
    from pcntoolkit.util.utils import squared_dist
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/util/__init__.py", line 1, in <module>
    from . import utils
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/util/utils.py", line 17, in <module>
    import pymc3 as pm
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/__init__.py", line 41, in <module>
    from .distributions import *
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/distributions/__init__.py", line 15, in <module>
    from . import timeseries
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/distributions/timeseries.py", line 22, in <module>
    from pymc3.util import get_variable_name
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/util.py", line 21, in <module>
    from numpy import asscalar, ndarray
ImportError: cannot import name 'asscalar' from 'numpy' (/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/numpy/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/trendsurf.py", line 21, in <module>
    from pcntoolkit.model.bayesreg import BLR
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/model/__init__.py", line 2, in <module>
    from . import gp
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/model/gp.py", line 25, in <module>
    from util.utils import squared_dist
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/util/__init__.py", line 1, in <module>
    from . import utils
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/util/utils.py", line 17, in <module>
    import pymc3 as pm
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/__init__.py", line 41, in <module>
    from .distributions import *
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/distributions/__init__.py", line 15, in <module>
    from . import timeseries
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/distributions/timeseries.py", line 22, in <module>
    from pymc3.util import get_variable_name
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/util.py", line 21, in <module>
    from numpy import asscalar, ndarray
ImportError: cannot import name 'asscalar' from 'numpy' (/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/numpy/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/model/gp.py", line 15, in <module>
    from pcntoolkit.util.utils import squared_dist
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/util/__init__.py", line 1, in <module>
    from . import utils
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/util/utils.py", line 17, in <module>
    import pymc3 as pm
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/__init__.py", line 41, in <module>
    from .distributions import *
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/distributions/__init__.py", line 15, in <module>
    from . import timeseries
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/distributions/timeseries.py", line 22, in <module>
    from pymc3.util import get_variable_name
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/util.py", line 21, in <module>
    from numpy import asscalar, ndarray
ImportError: cannot import name 'asscalar' from 'numpy' (/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/numpy/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/__init__.py", line 1, in <module>
    from . import trendsurf
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/trendsurf.py", line 30, in <module>
    from model.bayesreg import BLR
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/model/__init__.py", line 2, in <module>
    from . import gp
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/model/gp.py", line 25, in <module>
    from util.utils import squared_dist
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/util/__init__.py", line 1, in <module>
    from . import utils
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pcntoolkit/util/utils.py", line 17, in <module>
    import pymc3 as pm
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/__init__.py", line 41, in <module>
    from .distributions import *
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/distributions/__init__.py", line 15, in <module>
    from . import timeseries
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/distributions/timeseries.py", line 22, in <module>
    from pymc3.util import get_variable_name
  File "/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/pymc3/util.py", line 21, in <module>
    from numpy import asscalar, ndarray
ImportError: cannot import name 'asscalar' from 'numpy' (/opt/homebrew/anaconda3/envs/norm-test-conda/lib/python3.10/site-packages/numpy/__init__.py)
```

**Comment by amarquand** [comment]
Hi - thanks for pointing this out. We are aware of some dependency issues between pymc3/theano and newer versions of numpy. We are planning on upgrading the infrastructure to PyMC v4 which I hope will fix this issue. However, that is a substantial operation that will take us some time. For now, I would suggest to run with the solution you have proposed, i.e. using a slightly older version of numpy.

**Comment by ajdneuro** [comment]
Hello,
I tried this work around, (numpy==1.22.4) but on import of pcntoolkit I get: AttributeError: module 'numpy.distutils.__config__' has no attribute 'blas_opt_info'

Any ideas for a solution, many thanks!

Alex

**Comment by amarquand** [comment]
Hi there - could you please try with a slightly earlier version of numpy ? For example I am using 1.21.2

**Comment by ajdneuro** [comment]
Hi Andre,

Thanks for your quick reply, when importing with numpy==1.21.2 I get the following error: TypeError: data type 'float128' not understood
Thank you for your help,
Alex

**Comment by amarquand** [comment]
Hi - as discussed, I think this is related to your environment and is unrelated to the issue mentioned above. Please try again using a clean environment as discussed separately via email.

**Comment by 9id9** [comment]
Hello, 
I have been having the same issue with importing pcntoolkit on my local device
This is the error I get:

line 2, in <module>
    from . import normative
  File "<fstring>", line 1
    (kwargs=)
           ^
SyntaxError: invalid syntax

Can you please tell me how I might solve this?

**Comment by amarquand** [comment]
Hi - I am not sure it is the same issue. Could you please provide the details of the environment you are running this on? Also please ensure you downgrade numpy to  <= 1.22 first (using conda). 

We are now alpha testing a new version which should solve the numpy dependency issue. it is not released yet, but if you want you can try to install from the development branch.

**Comment by 9id9** [comment]
Exactly as the instructions, I downgraded numpy to 1.21.2 using conda, and ran the code with python 3.7.7

**Comment by amarquand** [comment]
Hi - this issue has been fixed with the newest release of the toolbox (0.28). Note that this was a major migration so not all of our tutorials will work at the moment, but we will update them in the coming weeks. Thanks for your patience!
